#!/bin/bash

echo "🚀 Quick Start Guide for GitHub + Cloudflare Pages"
echo ""
echo "STEP 1: Configure Git"
echo "Run: git config --global user.name 'Your Name'"
echo "Run: git config --global user.email 'your.email@example.com'"
echo ""
echo "STEP 2: Create GitHub repo at https://github.com/new"
echo "  - Name: relayo"
echo "  - Public: ✅"
echo "  - Don't initialize with README"
echo ""
echo "STEP 3: After creating repo, run these commands:"
echo "  cd /Users/mac/Desktop/Relayo"
echo "  git add ."
echo "  git commit -m 'Initial commit'"
echo "  git remote add origin https://github.com/YOUR_USERNAME/relayo.git"
echo "  git push -u origin main"
echo ""
echo "STEP 4: Go to Cloudflare Dashboard → Workers & Pages → Connect to Git"
echo ""
echo "📖 Full guide saved in: GITHUB_SETUP.md"
